basic_params:
  R_ring: 0.05            # Radius of ring array [m].
  N_transducer: 512       # Number of transducers.
  T_sample: 2.5e-8        # Sampling period [s].
  dx: 4.e-5               # Resolution of X coordinates [m].
  dy: 4.e-5               # Resolution of Y coordinates [m].
  N_patch: 80             # Size of isoplanatic patch in pixels.
  l_patch: 3.2e-3         # Size of image patch [m].
  fwhm: 1.5e-3            # FWHM of Gaussian window [m].


numerical:
  task: "numerical"
  description: "numerical phantom"
  sinogram: "sinogram_simulation_easy.mat"
  EIR: null
  ring_error: null
  SOS: "SoS_simulation_easy.mat"

  t0: 0
  Nx: 560                 # Image size in X direction.
  Ny: 560                 # Image size in Y direction.
  x_c: 0.0
  y_c: 0.0
  T: 26.0                 # Water temperature [C].
  R_body: 9.8e-3               # Radius of body [m].

  mean: 1550.0            # Mean of SOS in tissue [m/s].
  std: 110.0              # Standard deviation of SOS in tissue [m/s].
  SOS_min: 1495
  SOS_max: 1605
  IP_min: -1
  IP_max: 5



phantom:
  task: "phantom"
  description: "leaf phantom"
  sinogram: "LEAF_PHANTOM.mat"
  EIR: "EIR_TUNGSTEN.mat"
  ring_error: "RING_ERROR_NEW.mat"
  SOS: null

  t0: 46
  Nx: 640                 # Image size in X direction.
  Ny: 640                 # Image size in Y direction.
  x_c: 20
  y_c: -45
  R_body: 12.5e-3              # Radius of body [m].
  T: 26.0                 # Water temperature [C].

  mean: 1530.0            # Mean of SOS in tissue [m/s].
  std: 10.5               # Standard deviation of SOS in tissue [m/s].
  SOS_min: 1495
  SOS_max: 1535
  IP_min: -3
  IP_max: 5


in_vivo:
  task: "in_vivo"
  description: "in vivo mouse liver"
  sinogram: "ANIMAL_LAYER.mat"
  EIR: "EIR_TUNGSTEN.mat"
  ring_error: "RING_ERROR_NEW.mat"
  SOS: null

  t0: 46
  Nx: 560                 # Image size in X direction.
  Ny: 560                 # Image size in Y direction.
  x_c: -26
  y_c: 15
  T: 31.0                 # Water temperature [C].
  R_body: 10.8e-3               # Radius of body [m].

  mean: 1530.0           # Mean of SOS in tissue [m/s].
  std: 28.0              # Standard deviation of SOS in tissue [m/s].  
  SOS_min: 1500
  SOS_max: 1580
  IP_min: -3
  IP_max: 8


kidney:
  task: "kidney"
  description: "in vivo mouse kidney"
  sinogram: "mouse_wholebody_sample_liver_RF.mat"
  EIR: "EIR_TUNGSTEN.mat"
  ring_error: "RING_ERROR_NEW.mat"
  SOS: null

  t0: 196
  Nx: 560                 # Image size in X direction.
  Ny: 560                 # Image size in Y direction.
  x_c: 0
  y_c: 0
  T: 31.0                 # Water temperature [C].
  R_body: 10.8e-3               # Radius of body [m].

  mean: 1540.0           # Mean of SOS in tissue [m/s].
  std: 50.0              # Standard deviation of SOS in tissue [m/s].  
  SOS_min: 1500
  SOS_max: 1580
  IP_min: -3
  IP_max: 8